version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    stdin_open: true